/**
 * Watchdog Service for Omni-Tool
 * Specifically designed to monitor runaway Web Workers (FFmpeg / ONNX)
 * and manage Local / OPFS Garbage Collection.
 */

export interface WatchdogConfig {
  timeoutMs: number;
  memoryLimitMb?: number;
}

export class OmniWatchdog {
  private static instance: OmniWatchdog;
  private watchList: Map<string, { worker: Worker; timer: NodeJS.Timeout }> = new Map();

  private constructor() {}

  static getInstance(): OmniWatchdog {
    if (!OmniWatchdog.instance) {
      OmniWatchdog.instance = new OmniWatchdog();
    }
    return OmniWatchdog.instance;
  }

  /**
   * Registers a high-intensity Web Worker (like FFmpeg) to the watchdog.
   * If the worker doesn't complete within the timeout, it will be forcefully terminated.
   */
  public watchWorker(id: string, worker: Worker, config: WatchdogConfig): void {
    if (this.watchList.has(id)) {
      this.clearWatch(id);
    }

    const timer = setTimeout(() => {
      console.error(`🚨 [Watchdog] Worker "${id}" exceeded timeout (${config.timeoutMs}ms). Terminating immediately to prevent memory starvation.`);
      worker.terminate();
      this.watchList.delete(id);
      
      // Notify the system that a panic termination occurred
      window.dispatchEvent(new CustomEvent('omni:watchdog-panic', { detail: { id } }));
    }, config.timeoutMs);

    this.watchList.set(id, { worker, timer });
    console.log(`👁️ [Watchdog] Monitoring worker "${id}" with strict ${config.timeoutMs}ms limit.`);
  }

  /**
   * Clears the watchdog timer for a worker that successfully completed its task.
   */
  public clearWatch(id: string): void {
    const entry = this.watchList.get(id);
    if (entry) {
      clearTimeout(entry.timer);
      this.watchList.delete(id);
      console.log(`✅ [Watchdog] Worker "${id}" completed safely. Watch cleared.`);
    }
  }

  /**
   * OPFS (Origin Private File System) garbage collection.
   * Clears orphaned temp files generated by WASM that weren't cleaned up by crashed workers.
   */
  public async purgeOPFSTempFiles(): Promise<void> {
    try {
      const root = await navigator.storage.getDirectory();
      const tempDir = await root.getDirectoryHandle('.omni-temp', { create: false }).catch(() => null);
      
      if (tempDir) {
        // Simple heuristic: delete entire temp directory and recreate it
        await root.removeEntry('.omni-temp', { recursive: true });
        console.warn('🗑️ [Watchdog] OPFS .omni-temp directory purged successfully.');
      }
    } catch (e) {
      console.error('[Watchdog] Failed to purge OPFS:', e);
    }
  }
}

export const watchdog = OmniWatchdog.getInstance();
