/**
 * Complete Genre Catalog — 27 genres with configuration parameters.
 */
export interface GenreDefinition {
  display_name: string;
  description: string;
  bpm_range: [number, number];
  scale: string;
  instruments: string[];
  lead_instrument: string;
  temperature: number;
  note_range: [number, number];
  velocity_range: [number, number];
  rest_probability: number;
  chord_types: string[];
  octave_range: [number, number];
  swing: number;
  reverb: number;
  delay_ms: number;
  delay_feedback: number;
  color: string;
}

export const GENRE_CATALOG: Record<string, GenreDefinition> = {
  'pop': {
    display_name: '🎤 Pop',
    description: 'Catchy melodies with simple chord progressions',
    bpm_range: [100, 130], scale: 'major',
    instruments: ['piano', 'synth_pad', 'bass', 'drums'],
    lead_instrument: 'piano', temperature: 0.75,
    note_range: [55, 79], velocity_range: [70, 110], rest_probability: 0.12,
    chord_types: ['major', 'minor', 'sus2', 'add9'], octave_range: [3, 5],
    swing: 0.0, reverb: 0.25, delay_ms: 200, delay_feedback: 0.2, color: '#ff6b9d',
  },
  'rock': {
    display_name: '🎸 Rock', description: 'Driving rhythms with power chords',
    bpm_range: [110, 145], scale: 'pentatonic_minor',
    instruments: ['electric_guitar', 'bass', 'drums', 'organ'],
    lead_instrument: 'electric_guitar', temperature: 0.8,
    note_range: [48, 76], velocity_range: [80, 127], rest_probability: 0.08,
    chord_types: ['power', 'major', 'minor', 'sus4'], octave_range: [3, 5],
    swing: 0.0, reverb: 0.3, delay_ms: 250, delay_feedback: 0.15, color: '#e74c3c',
  },
  'blues': {
    display_name: '🎵 Blues', description: 'Soulful melodies with blue notes',
    bpm_range: [70, 120], scale: 'blues',
    instruments: ['electric_guitar', 'piano', 'bass', 'drums'],
    lead_instrument: 'electric_guitar', temperature: 0.85,
    note_range: [48, 76], velocity_range: [60, 110], rest_probability: 0.15,
    chord_types: ['dom7', 'dom9', 'minor', 'major'], octave_range: [3, 5],
    swing: 0.3, reverb: 0.3, delay_ms: 300, delay_feedback: 0.2, color: '#3498db',
  },
  'jazz': {
    display_name: '🎷 Jazz', description: 'Complex harmonies with improvisation',
    bpm_range: [80, 180], scale: 'dorian',
    instruments: ['piano', 'saxophone', 'double_bass', 'drums'],
    lead_instrument: 'piano', temperature: 0.92,
    note_range: [48, 84], velocity_range: [50, 100], rest_probability: 0.18,
    chord_types: ['maj7', 'min7', 'dom7', 'half_dim7', 'dim7', 'dom9', 'min9'], octave_range: [3, 6],
    swing: 0.4, reverb: 0.35, delay_ms: 150, delay_feedback: 0.1, color: '#9b59b6',
  },
  'classical': {
    display_name: '🎻 Classical', description: 'Elegant compositions with rich harmonies',
    bpm_range: [60, 140], scale: 'major',
    instruments: ['piano', 'strings', 'flute', 'cello'],
    lead_instrument: 'piano', temperature: 0.7,
    note_range: [40, 88], velocity_range: [40, 110], rest_probability: 0.1,
    chord_types: ['major', 'minor', 'diminished', 'augmented', 'dom7'], octave_range: [3, 6],
    swing: 0.0, reverb: 0.5, delay_ms: 50, delay_feedback: 0.05, color: '#f1c40f',
  },
  'electronic': {
    display_name: '🎹 Electronic', description: 'Pulsing synths with driving beats',
    bpm_range: [120, 150], scale: 'natural_minor',
    instruments: ['synth_lead', 'synth_pad', 'bass', 'drums'],
    lead_instrument: 'synth_lead', temperature: 0.85,
    note_range: [36, 84], velocity_range: [80, 120], rest_probability: 0.05,
    chord_types: ['minor', 'sus2', 'sus4', 'power'], octave_range: [3, 6],
    swing: 0.0, reverb: 0.4, delay_ms: 375, delay_feedback: 0.35, color: '#00d4ff',
  },
  'ambient': {
    display_name: '🌊 Ambient', description: 'Ethereal soundscapes for relaxation',
    bpm_range: [50, 90], scale: 'lydian',
    instruments: ['synth_pad', 'strings', 'flute', 'bells'],
    lead_instrument: 'synth_pad', temperature: 0.95,
    note_range: [48, 84], velocity_range: [30, 80], rest_probability: 0.25,
    chord_types: ['maj7', 'add9', 'sus2', 'maj9'], octave_range: [3, 6],
    swing: 0.0, reverb: 0.7, delay_ms: 600, delay_feedback: 0.5, color: '#1abc9c',
  },
  'rnb': {
    display_name: '🎙️ R&B', description: 'Smooth grooves with soulful melodies',
    bpm_range: [65, 100], scale: 'dorian',
    instruments: ['piano', 'synth_pad', 'bass', 'drums'],
    lead_instrument: 'piano', temperature: 0.8,
    note_range: [50, 79], velocity_range: [55, 100], rest_probability: 0.15,
    chord_types: ['min7', 'maj7', 'dom7', 'min9', 'add9'], octave_range: [3, 5],
    swing: 0.2, reverb: 0.35, delay_ms: 250, delay_feedback: 0.2, color: '#e056a0',
  },
  'hiphop': {
    display_name: '🎤 Hip Hop', description: 'Heavy beats with melodic hooks',
    bpm_range: [80, 110], scale: 'natural_minor',
    instruments: ['piano', 'synth_lead', 'bass_808', 'drums'],
    lead_instrument: 'piano', temperature: 0.82,
    note_range: [36, 76], velocity_range: [70, 120], rest_probability: 0.12,
    chord_types: ['minor', 'min7', 'dom7', 'sus2'], octave_range: [2, 5],
    swing: 0.15, reverb: 0.25, delay_ms: 300, delay_feedback: 0.25, color: '#f39c12',
  },
  'country': {
    display_name: '🤠 Country', description: 'Heartfelt melodies with twangy guitars',
    bpm_range: [95, 140], scale: 'major',
    instruments: ['acoustic_guitar', 'piano', 'bass', 'drums'],
    lead_instrument: 'acoustic_guitar', temperature: 0.72,
    note_range: [50, 79], velocity_range: [65, 105], rest_probability: 0.1,
    chord_types: ['major', 'minor', 'dom7', 'sus4'], octave_range: [3, 5],
    swing: 0.1, reverb: 0.2, delay_ms: 200, delay_feedback: 0.15, color: '#d4a574',
  },
  'reggae': {
    display_name: '🇯🇲 Reggae', description: 'Offbeat rhythms with island vibes',
    bpm_range: [65, 95], scale: 'major',
    instruments: ['electric_guitar', 'organ', 'bass', 'drums'],
    lead_instrument: 'organ', temperature: 0.78,
    note_range: [48, 76], velocity_range: [60, 95], rest_probability: 0.15,
    chord_types: ['major', 'minor', 'dom7'], octave_range: [3, 5],
    swing: 0.0, reverb: 0.3, delay_ms: 375, delay_feedback: 0.3, color: '#27ae60',
  },
  'latin': {
    display_name: '💃 Latin', description: 'Rhythmic and passionate melodies',
    bpm_range: [90, 130], scale: 'harmonic_minor',
    instruments: ['acoustic_guitar', 'piano', 'bass', 'percussion'],
    lead_instrument: 'acoustic_guitar', temperature: 0.82,
    note_range: [48, 79], velocity_range: [70, 115], rest_probability: 0.1,
    chord_types: ['minor', 'major', 'dom7', 'min7'], octave_range: [3, 5],
    swing: 0.1, reverb: 0.25, delay_ms: 200, delay_feedback: 0.15, color: '#e67e22',
  },
  'metal': {
    display_name: '🤘 Metal', description: 'Aggressive riffs with heavy distortion',
    bpm_range: [100, 200], scale: 'phrygian',
    instruments: ['electric_guitar', 'bass', 'drums', 'organ'],
    lead_instrument: 'electric_guitar', temperature: 0.88,
    note_range: [36, 76], velocity_range: [90, 127], rest_probability: 0.05,
    chord_types: ['power', 'minor', 'diminished'], octave_range: [2, 5],
    swing: 0.0, reverb: 0.2, delay_ms: 100, delay_feedback: 0.1, color: '#2c3e50',
  },
  'funk': {
    display_name: '🕺 Funk', description: 'Groovy bass lines with syncopation',
    bpm_range: [95, 125], scale: 'mixolydian',
    instruments: ['electric_guitar', 'bass', 'organ', 'drums'],
    lead_instrument: 'electric_guitar', temperature: 0.85,
    note_range: [36, 76], velocity_range: [75, 120], rest_probability: 0.08,
    chord_types: ['dom7', 'min7', 'dom9', 'dom7sus4'], octave_range: [2, 5],
    swing: 0.25, reverb: 0.2, delay_ms: 150, delay_feedback: 0.1, color: '#8e44ad',
  },
  'gospel': {
    display_name: '⛪ Gospel', description: 'Uplifting harmonies with spiritual energy',
    bpm_range: [80, 130], scale: 'major',
    instruments: ['piano', 'organ', 'bass', 'drums'],
    lead_instrument: 'organ', temperature: 0.78,
    note_range: [48, 84], velocity_range: [65, 115], rest_probability: 0.1,
    chord_types: ['major', 'minor', 'dom7', 'maj7', 'add9'], octave_range: [3, 6],
    swing: 0.15, reverb: 0.45, delay_ms: 200, delay_feedback: 0.15, color: '#f0c27f',
  },
  'celtic': {
    display_name: '🍀 Celtic', description: 'Folk melodies with traditional instruments',
    bpm_range: [90, 140], scale: 'mixolydian',
    instruments: ['flute', 'acoustic_guitar', 'violin', 'drums'],
    lead_instrument: 'flute', temperature: 0.75,
    note_range: [55, 84], velocity_range: [55, 100], rest_probability: 0.1,
    chord_types: ['major', 'minor', 'sus4', 'sus2'], octave_range: [4, 6],
    swing: 0.0, reverb: 0.3, delay_ms: 200, delay_feedback: 0.15, color: '#2ecc71',
  },
  'middle_eastern': {
    display_name: '🕌 Middle Eastern', description: 'Exotic scales with ornamental melodies',
    bpm_range: [80, 130], scale: 'phrygian_dominant',
    instruments: ['oud', 'piano', 'bass', 'percussion'],
    lead_instrument: 'piano', temperature: 0.88,
    note_range: [48, 79], velocity_range: [55, 105], rest_probability: 0.12,
    chord_types: ['major', 'minor', 'sus2', 'dom7'], octave_range: [3, 5],
    swing: 0.0, reverb: 0.35, delay_ms: 250, delay_feedback: 0.2, color: '#c0392b',
  },
  'cinematic': {
    display_name: '🎬 Cinematic', description: 'Epic orchestral compositions',
    bpm_range: [60, 140], scale: 'natural_minor',
    instruments: ['strings', 'piano', 'brass', 'drums'],
    lead_instrument: 'strings', temperature: 0.82,
    note_range: [36, 88], velocity_range: [40, 127], rest_probability: 0.1,
    chord_types: ['major', 'minor', 'sus2', 'sus4', 'augmented'], octave_range: [2, 6],
    swing: 0.0, reverb: 0.55, delay_ms: 400, delay_feedback: 0.2, color: '#34495e',
  },
  'lofi': {
    display_name: '📻 Lo-Fi', description: 'Chill beats with warm vintage textures',
    bpm_range: [70, 90], scale: 'dorian',
    instruments: ['piano', 'synth_pad', 'bass', 'drums'],
    lead_instrument: 'piano', temperature: 0.82,
    note_range: [48, 76], velocity_range: [45, 85], rest_probability: 0.18,
    chord_types: ['min7', 'maj7', 'min9', 'dom7', 'add9'], octave_range: [3, 5],
    swing: 0.2, reverb: 0.4, delay_ms: 350, delay_feedback: 0.25, color: '#a29bfe',
  },
  'trap': {
    display_name: '🔊 Trap', description: 'Dark melodies with 808 bass and hi-hats',
    bpm_range: [130, 170], scale: 'phrygian',
    instruments: ['synth_lead', 'bass_808', 'drums', 'synth_pad'],
    lead_instrument: 'synth_lead', temperature: 0.88,
    note_range: [24, 72], velocity_range: [80, 127], rest_probability: 0.1,
    chord_types: ['minor', 'dim7', 'min7', 'sus2'], octave_range: [2, 5],
    swing: 0.0, reverb: 0.3, delay_ms: 250, delay_feedback: 0.2, color: '#6c5ce7',
  },
  'synthwave': {
    display_name: '🌆 Synthwave', description: '80s-inspired retro synthesizer music',
    bpm_range: [100, 130], scale: 'natural_minor',
    instruments: ['synth_lead', 'synth_pad', 'bass', 'drums'],
    lead_instrument: 'synth_lead', temperature: 0.8,
    note_range: [36, 84], velocity_range: [70, 110], rest_probability: 0.08,
    chord_types: ['major', 'minor', 'sus4', 'add9'], octave_range: [3, 6],
    swing: 0.0, reverb: 0.45, delay_ms: 375, delay_feedback: 0.35, color: '#fd79a8',
  },
  'disco': {
    display_name: '🪩 Disco', description: 'Groovy dance music with driving basslines',
    bpm_range: [115, 135], scale: 'major',
    instruments: ['synth_lead', 'bass', 'strings', 'drums'],
    lead_instrument: 'synth_lead', temperature: 0.78,
    note_range: [48, 79], velocity_range: [75, 115], rest_probability: 0.05,
    chord_types: ['major', 'minor', 'dom7', 'min7'], octave_range: [3, 5],
    swing: 0.1, reverb: 0.3, delay_ms: 200, delay_feedback: 0.2, color: '#fdcb6e',
  },
  'bossa_nova': {
    display_name: '🌴 Bossa Nova', description: 'Gentle Brazilian rhythms with jazz harmony',
    bpm_range: [110, 140], scale: 'major',
    instruments: ['acoustic_guitar', 'piano', 'double_bass', 'percussion'],
    lead_instrument: 'acoustic_guitar', temperature: 0.82,
    note_range: [48, 79], velocity_range: [45, 85], rest_probability: 0.15,
    chord_types: ['maj7', 'min7', 'dom7', 'dim7', 'min9'], octave_range: [3, 5],
    swing: 0.15, reverb: 0.3, delay_ms: 200, delay_feedback: 0.1, color: '#55efc4',
  },
  'waltz': {
    display_name: '💃 Waltz', description: 'Elegant 3/4 time dance music',
    bpm_range: [80, 140], scale: 'major',
    instruments: ['piano', 'strings', 'flute', 'cello'],
    lead_instrument: 'piano', temperature: 0.7,
    note_range: [48, 84], velocity_range: [50, 100], rest_probability: 0.1,
    chord_types: ['major', 'minor', 'dom7', 'diminished'], octave_range: [3, 6],
    swing: 0.0, reverb: 0.45, delay_ms: 100, delay_feedback: 0.05, color: '#dfe6e9',
  },
  'flamenco': {
    display_name: '🇪🇸 Flamenco', description: 'Passionate Spanish guitar with intricate rhythms',
    bpm_range: [80, 140], scale: 'phrygian_dominant',
    instruments: ['acoustic_guitar', 'percussion', 'bass', 'piano'],
    lead_instrument: 'acoustic_guitar', temperature: 0.9,
    note_range: [48, 84], velocity_range: [60, 120], rest_probability: 0.08,
    chord_types: ['major', 'minor', 'dom7', 'sus4'], octave_range: [3, 6],
    swing: 0.0, reverb: 0.25, delay_ms: 150, delay_feedback: 0.1, color: '#e17055',
  },
  'dnb': {
    display_name: '🥁 Drum & Bass', description: 'Fast breakbeats with deep basslines',
    bpm_range: [160, 180], scale: 'natural_minor',
    instruments: ['synth_lead', 'bass', 'synth_pad', 'drums'],
    lead_instrument: 'synth_lead', temperature: 0.88,
    note_range: [24, 76], velocity_range: [80, 125], rest_probability: 0.08,
    chord_types: ['minor', 'sus2', 'power', 'min7'], octave_range: [2, 5],
    swing: 0.0, reverb: 0.3, delay_ms: 187, delay_feedback: 0.25, color: '#00b894',
  },
  'dubstep': {
    display_name: '🔈 Dubstep', description: 'Heavy wobble bass with half-time beats',
    bpm_range: [138, 142], scale: 'phrygian',
    instruments: ['synth_lead', 'bass_wobble', 'synth_pad', 'drums'],
    lead_instrument: 'synth_lead', temperature: 0.9,
    note_range: [24, 72], velocity_range: [90, 127], rest_probability: 0.1,
    chord_types: ['minor', 'power', 'diminished', 'sus2'], octave_range: [2, 5],
    swing: 0.0, reverb: 0.25, delay_ms: 220, delay_feedback: 0.2, color: '#636e72',
  },
};
