import { Routes } from '@angular/router';

export const PDF_ROUTES: Routes = [
  { path: 'merger', loadComponent: () => import('./01-merger').then(m => m.MergerComponent) },
  { path: 'splitter', loadComponent: () => import('./02-splitter').then(m => m.SplitterComponent) },
  { path: 'compressor', loadComponent: () => import('./03-compressor').then(m => m.CompressorComponent) },
  { path: 'converter', loadComponent: () => import('./04-converter').then(m => m.ConverterComponent) },
  { path: 'ocr', loadComponent: () => import('./05-ocr').then(m => m.OcrComponent) },
  { path: 'watermark', loadComponent: () => import('./06-watermark').then(m => m.WatermarkComponent) },
  { path: 'passwordProtector', loadComponent: () => import('./07-password-protector').then(m => m.PasswordProtectorComponent) },
  { path: 'unlocker', loadComponent: () => import('./08-unlocker').then(m => m.UnlockerComponent) },
  { path: 'rotator', loadComponent: () => import('./09-rotator').then(m => m.RotatorComponent) },
  { path: 'cropResize', loadComponent: () => import('./10-crop-resize').then(m => m.CropResizeComponent) },
  { path: 'imageExtractor', loadComponent: () => import('./11-image-extractor').then(m => m.ImageExtractorComponent) },
  { path: 'textExtractor', loadComponent: () => import('./12-text-extractor').then(m => m.TextExtractorComponent) },
  { path: 'metadataEditor', loadComponent: () => import('./13-metadata-editor').then(m => m.MetadataEditorComponent) },
  { path: 'digitalSigner', loadComponent: () => import('./14-digital-signer').then(m => m.DigitalSignerComponent) },
  { path: 'redactor', loadComponent: () => import('./15-redactor').then(m => m.RedactorComponent) },
  { path: 'annotator', loadComponent: () => import('./16-annotator').then(m => m.AnnotatorComponent) },
  { path: 'formFiller', loadComponent: () => import('./17-form-filler').then(m => m.FormFillerComponent) },
  { path: 'pageReorderer', loadComponent: () => import('./18-page-reorderer').then(m => m.PageReordererComponent) },
  { path: 'thumbnailGenerator', loadComponent: () => import('./19-thumbnail-generator').then(m => m.ThumbnailGeneratorComponent) },
  { path: 'compare', loadComponent: () => import('./20-compare').then(m => m.CompareComponent) },
  { path: 'toWord', loadComponent: () => import('./21-to-word').then(m => m.ToWordComponent) },
  { path: 'toExcel', loadComponent: () => import('./22-to-excel').then(m => m.ToExcelComponent) },
  { path: 'toPowerpoint', loadComponent: () => import('./23-to-powerpoint').then(m => m.ToPowerpointComponent) },
  { path: 'toHtml', loadComponent: () => import('./24-to-html').then(m => m.ToHtmlComponent) },
  { path: 'toImageBatch', loadComponent: () => import('./25-to-image-batch').then(m => m.ToImageBatchComponent) },
  { path: 'repair', loadComponent: () => import('./26-repair').then(m => m.RepairComponent) },
  { path: 'flattener', loadComponent: () => import('./27-flattener').then(m => m.FlattenerComponent) },
  { path: 'optimizer', loadComponent: () => import('./28-optimizer').then(m => m.OptimizerComponent) },
  { path: 'bookmarkEditor', loadComponent: () => import('./29-bookmark-editor').then(m => m.BookmarkEditorComponent) },
  { path: 'batchProcessor', loadComponent: () => import('./30-batch-processor').then(m => m.BatchProcessorComponent) }
];
