import { 
  Video, 
  Zap, 
  Scissors, 
  Layers, 
  Type, 
  VolumeX, 
  Music, 
  Stamp, 
  FastForward, 
  RotateCcw, 
  RotateCw, 
  Crop, 
  Maximize, 
  Image as ImageIcon, 
  Film, 
  Camera, 
  Radio, 
  Monitor, 
  Video as VideoIcon, 
  Sliders, 
  ArrowUpCircle, 
  Wind, 
  Activity, 
  Languages, 
  Search, 
  Info, 
  Lock, 
  Download, 
  Share2, 
  Boxes 
} from "lucide-react";

export const VIDEO_TOOLS = [
  { id: "converter", name: "Video Converter", desc: "Convert between MP4, AVI, MKV, etc.", icon: Video, color: "text-blue-500" },
  { id: "compressor", name: "Video Compressor", desc: "Reduce video file size", icon: Zap, color: "text-yellow-500" },
  { id: "cutter", name: "Video Cutter", desc: "Trim and cut video segments", icon: Scissors, color: "text-red-500" },
  { id: "merger", name: "Merge Video", desc: "Combine multiple videos into one", icon: Layers, color: "text-emerald-500" },
  { id: "subtitle", name: "Add Subtitle", desc: "Burn subtitles into video", icon: Type, color: "text-indigo-500" },
  { id: "remove-audio", name: "Remove Audio", desc: "Mute video completely", icon: VolumeX, color: "text-slate-500" },
  { id: "extract-audio", name: "Extract Audio", desc: "Save audio as MP3/WAV", icon: Music, color: "text-pink-500" },
  { id: "watermark", name: "Watermark Video", desc: "Add text or image watermark", icon: Stamp, color: "text-orange-500" },
  { id: "speed", name: "Speed Controller", desc: "Slow motion or fast forward", icon: FastForward, color: "text-cyan-500" },
  { id: "reverse", name: "Reverse Video", desc: "Play video backwards", icon: RotateCcw, color: "text-purple-500" },
  { id: "rotate", name: "Rotate Video", desc: "Rotate 90, 180, 270 degrees", icon: RotateCw, color: "text-amber-500" },
  { id: "crop", name: "Crop Video", desc: "Change video aspect ratio", icon: Crop, color: "text-lime-500" },
  { id: "resize", name: "Resize Resolution", desc: "Change width and height", icon: Maximize, color: "text-sky-500" },
  { id: "frame-extractor", name: "Frame Extractor", desc: "Extract frames as images", icon: ImageIcon, color: "text-rose-500" },
  { id: "gif-generator", name: "GIF Generator", desc: "Convert video to animated GIF", icon: Film, color: "text-fuchsia-500" },
  { id: "thumbnail", name: "Thumbnail Generator", desc: "Create custom thumbnails", icon: Camera, color: "text-teal-500" },
  { id: "live-stream", name: "Live Streaming", desc: "Broadcast to RTMP/HLS", icon: Radio, color: "text-red-600" },
  { id: "screen-recorder", name: "Screen Recorder", desc: "Capture your desktop", icon: Monitor, color: "text-blue-600" },
  { id: "webcam-recorder", name: "Webcam Recorder", desc: "Record from camera", icon: VideoIcon, color: "text-green-600" },
  { id: "filters", name: "Video Filters", desc: "Brightness, contrast, effects", icon: Sliders, color: "text-violet-600" },
  { id: "upscaling", name: "AI Upscaling", desc: "Enhance video quality", icon: ArrowUpCircle, color: "text-yellow-600" },
  { id: "noise-reduction", name: "Noise Reduction", desc: "Clean up grainy video", icon: Wind, color: "text-slate-400" },
  { id: "stabilization", name: "Stabilization", desc: "Fix shaky camera footage", icon: Activity, color: "text-emerald-600" },
  { id: "auto-subtitle", name: "Auto Subtitle", desc: "AI-powered transcription", icon: Languages, color: "text-indigo-600" },
  { id: "scene-detection", name: "Scene Detection", desc: "Identify scene changes", icon: Search, color: "text-orange-600" },
  { id: "metadata", name: "Metadata Editor", desc: "Edit title, author, tags", icon: Info, color: "text-blue-400" },
  { id: "encryption", name: "Video Encryption", desc: "Secure your video files", icon: Lock, color: "text-red-400" },
  { id: "downloader", name: "Video Downloader", desc: "Save videos from web", icon: Download, color: "text-green-400" },
  { id: "hls-generator", name: "HLS Generator", desc: "Create streaming segments", icon: Share2, color: "text-pink-400" },
  { id: "batch", name: "Batch Processing", desc: "Process multiple files", icon: Boxes, color: "text-purple-400" },
];
