// ============================================================
// GEMINI IMAGE AI SERVICE — Multi-Key Failover
// File: src/app/modules/image-matrix/services/gemini-image.service.ts
// ============================================================

import { Injectable } from '@angular/core';

/**
 * Response structure from Gemini API image operations
 */
export interface GeminiImageResult {
  success: boolean;
  data?: Blob;
  text?: string;
  error?: string;
}

/**
 * Configuration for image edit requests
 */
export interface GeminiEditConfig {
  file: File;
  prompt: string;
  mimeType?: string;
}

const API_KEYS: string[] = [
  'AIzaSyDkcAGrhLQ154GpZjOvrUJQZP1Btw0JkxE',
  'AIzaSyBMSQEA4FiQHCLvw93Fn6Gj6y-VyF8V7to',
  'AIzaSyDnne5UW0Ha-ccXA10vRLZppNVLsQeKcBM',
  'AIzaSyA_b8jIUCqYj_0aud9Wbql__R0MzTpdVmY'
];

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta';

@Injectable({ providedIn: 'root' })
export class GeminiImageService {
  private currentKeyIndex = 0;
  private readonly maxRetries = API_KEYS.length;

  /**
   * Get the current active API key
   */
  private get apiKey(): string {
    return API_KEYS[this.currentKeyIndex];
  }

  /**
   * Rotate to the next API key
   */
  private rotateKey(): void {
    this.currentKeyIndex = (this.currentKeyIndex + 1) % API_KEYS.length;
    console.warn(`[GeminiImageService] Rotated to API key index: ${this.currentKeyIndex}`);
  }

  /**
   * Convert a File to base64 data URI string
   */
  private fileToBase64(file: File): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const result = reader.result as string;
        const base64 = result.split(',')[1];
        resolve(base64);
      };
      reader.onerror = () => reject(new Error('Failed to read file'));
      reader.readAsDataURL(file);
    });
  }

  /**
   * Send an image editing request to Gemini with auto key failover
   */
  async editImage(config: GeminiEditConfig): Promise<GeminiImageResult> {
    const base64Data = await this.fileToBase64(config.file);
    const mimeType = config.mimeType || config.file.type || 'image/png';

    for (let attempt = 0; attempt < this.maxRetries; attempt++) {
      try {
        const url = `${GEMINI_API_BASE}/models/gemini-2.0-flash-exp-image-generation:generateContent?key=${this.apiKey}`;

        const body = {
          contents: [{
            parts: [
              { text: config.prompt },
              {
                inlineData: {
                  mimeType,
                  data: base64Data
                }
              }
            ]
          }],
          generationConfig: {
            responseModalities: ['TEXT', 'IMAGE']
          }
        };

        const response = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(body)
        });

        if (response.status === 429 || response.status === 403) {
          console.warn(`[GeminiImageService] Key ${this.currentKeyIndex} rate-limited. Rotating...`);
          this.rotateKey();
          continue;
        }

        if (!response.ok) {
          const errText = await response.text();
          return { success: false, error: `API Error ${response.status}: ${errText}` };
        }

        const json = await response.json();
        const candidates = json.candidates;

        if (!candidates || candidates.length === 0) {
          return { success: false, error: 'No response generated by AI' };
        }

        const parts = candidates[0]?.content?.parts ?? [];

        let resultBlob: Blob | undefined;
        let resultText: string | undefined;

        for (const part of parts) {
          if (part.inlineData) {
            const binaryStr = atob(part.inlineData.data);
            const bytes = new Uint8Array(binaryStr.length);
            for (let i = 0; i < binaryStr.length; i++) {
              bytes[i] = binaryStr.charCodeAt(i);
            }
            resultBlob = new Blob([bytes], { type: part.inlineData.mimeType || 'image/png' });
          }
          if (part.text) {
            resultText = part.text;
          }
        }

        return { success: true, data: resultBlob, text: resultText };

      } catch (err) {
        console.error(`[GeminiImageService] Attempt ${attempt + 1} failed:`, err);
        this.rotateKey();
      }
    }

    return { success: false, error: 'All API keys exhausted. Please try again later.' };
  }

  /**
   * Describe/caption an image using Gemini
   */
  async describeImage(file: File, prompt?: string): Promise<GeminiImageResult> {
    const base64Data = await this.fileToBase64(file);
    const mimeType = file.type || 'image/png';
    const textPrompt = prompt || 'Describe this image in detail. Provide a comprehensive description including objects, colors, composition, mood, and any text visible.';

    for (let attempt = 0; attempt < this.maxRetries; attempt++) {
      try {
        const url = `${GEMINI_API_BASE}/models/gemini-2.0-flash:generateContent?key=${this.apiKey}`;

        const body = {
          contents: [{
            parts: [
              { text: textPrompt },
              {
                inlineData: {
                  mimeType,
                  data: base64Data
                }
              }
            ]
          }]
        };

        const response = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(body)
        });

        if (response.status === 429 || response.status === 403) {
          this.rotateKey();
          continue;
        }

        if (!response.ok) {
          const errText = await response.text();
          return { success: false, error: `API Error ${response.status}: ${errText}` };
        }

        const json = await response.json();
        const text = json.candidates?.[0]?.content?.parts?.[0]?.text;

        return { success: true, text: text || 'No description generated.' };
      } catch (err) {
        console.error(`[GeminiImageService] describeImage attempt ${attempt + 1} failed:`, err);
        this.rotateKey();
      }
    }

    return { success: false, error: 'All API keys exhausted.' };
  }
}
